apiVersion: v2
name: devx-helloworld-springboot-test-zgiqv
description: Chart for creating devx-helloworld-springboot-test-zgiqv and ingress mapping our Flexport EKS clusters

type: application
version: 0.1.0
