config:
  host: devx-helloworld-springboot-test-zgiqv.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-test-zgiqv-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-test-zgiqv-docker-dev-local/devx-helloworld-springboot-test-zgiqv
    tag: 0.0.1-SNAPSHOT
